### ISSUE TITLE
Answer why CyberD is better for Web3 then Google

### ISSUE THREAD

**Issue by npopeka** [cybercongress/cyberd#328]
In general you can find out IPFS hash only if you uploaded content or have access to IPFS node and able to use 'ipfs refs local' command. So only content creator can index IPFS hash as a CiD.
Google wont be able to search in IPFS  ever, because he wont be able to get CiD's from IPFS.

**Comment by xhipster** [comment]
Loading search result directly from IPFS :-) Yeees!

**Comment by xhipster** [comment]
I have added the following arguments in the whitepaper:

During implementation of proposed architecture we realize at least 3 key benefits a Google probab;y would not be able to deliver with conventiaon approach:

- search result can be easily delivered from p2p network right into search results: eg. .cyber can play video.
- payment buttons can be embedded right into search snippets, so web3 agent can interact with search results, eg. agents can buy an items right in .cyber. Also so e-commerce can flourish because of transparent conversion attribution.
- search snippets must not be static but can be interactive, eg. .cyber eventually can answer location based answers.
I am sure this answer the question completely
